### ISSUE TITLE
Issue entering Kibana using port 64297: Kibana server is not ready yet.

### ISSUE THREAD

**Issue by itai77** [telekom-security/tpotce#1161]
Basic Information:

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
- 
![image](https://user-images.githubusercontent.com/76133207/185783602-6ff87206-108e-426a-9e31-892015cd0ad1.png)
![image](https://user-images.githubusercontent.com/76133207/185783628-656fdd59-954b-4594-975e-5e9498ce5e93.png)

- What T-Pot version are you currently using?
- Latest
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
- Standard
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
- AWS instance
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- no
- How long has your installation been running?
- about a week and a half
- Did you install upgrades, packages or use the update script?
- no
- Did you modify any scripts or configs? If yes, please attach the changes.
- no
- Please provide a screenshot of `glances` and `htop`.
- 
![image](https://user-images.githubusercontent.com/76133207/185783764-f0b25bfb-fed3-4b13-b9be-6f478b34bf6c.png)
![image](https://user-images.githubusercontent.com/76133207/185783778-77407a3c-f74a-4fda-a8ce-df1e8337dc2f.png)

- How much free disk space is available (`df -h`)?
- 
![image](https://user-images.githubusercontent.com/76133207/185783792-77ead672-676c-45d6-abad-baccd4bab86d.png)

- What is the current container status (`dps.sh`)?
- 
![image](https://user-images.githubusercontent.com/76133207/185783830-fdc13da7-5ef7-4bba-98b1-b1622a7e89f3.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
- 
![image](https://user-images.githubusercontent.com/76133207/185783867-50f59a67-58e2-42bb-909c-01565367d660.png)

My issue:
Server seems to be up and running however when I try to enter Kibana using port 64297 I get this message: 
Kibana server is not ready yet.

I tried rebooting my AWS instance but that didn't help.

Thanks!

**Comment by t3chn0m4g3** [comment]
Please check and post the logs ...

```
docker logs kibana
docker logs elasticsearch
```

**Comment by itai77** [comment]
Thanks for the quick reply!

docker logs kibana
![image](https://user-images.githubusercontent.com/76133207/185786992-b96aef4d-68b1-4daf-92dd-204b90ac9d7b.png)

docker logs elasticsearch

`[admin@coolcalm:~]$ sudo docker logs elasticsearch
sudo: unable to resolve host coolcalm: Name or service not known
[2022-08-21T08:06:05,506][INFO ][o.e.n.Node               ] [tpotcluster-node-01] version[8.2.3], pid[1], build[default/deb/9905bfb62a3f0b044948376b4f607f70a8a151b4/2022-06-08T22:21:36.455508792Z], OS[Linux/5.10.0-17-cloud-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/18.0.1.1/18.0.1.1+2-6]
[2022-08-21T08:06:05,554][INFO ][o.e.n.Node               ] [tpotcluster-node-01] JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]
[2022-08-21T08:06:05,555][INFO ][o.e.n.Node               ] [tpotcluster-node-01] JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/elasticsearch, -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Xms2048m, -Xmx2048m, -XX:MaxDirectMemorySize=1073741824, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/etc/elasticsearch, -Des.distribution.flavor=default, -Des.distribution.type=deb, -Des.bundled_jdk=true]
[2022-08-21T08:06:20,160][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [aggs-matrix-stats]
[2022-08-21T08:06:20,180][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [analysis-common]
[2022-08-21T08:06:20,184][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [constant-keyword]
[2022-08-21T08:06:20,185][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [data-streams]
[2022-08-21T08:06:20,188][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [frozen-indices]
[2022-08-21T08:06:20,189][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [ingest-common]
[2022-08-21T08:06:20,191][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [ingest-geoip]
[2022-08-21T08:06:20,202][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [ingest-user-agent]
[2022-08-21T08:06:20,202][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [kibana]
[2022-08-21T08:06:20,203][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [lang-expression]
[2022-08-21T08:06:20,203][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [lang-mustache]
[2022-08-21T08:06:20,204][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [lang-painless]
[2022-08-21T08:06:20,204][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [legacy-geo]
[2022-08-21T08:06:20,205][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [mapper-extras]
[2022-08-21T08:06:20,205][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [mapper-version]
[2022-08-21T08:06:20,205][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [parent-join]
[2022-08-21T08:06:20,206][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [percolator]
[2022-08-21T08:06:20,206][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [rank-eval]
[2022-08-21T08:06:20,207][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [reindex]
[2022-08-21T08:06:20,211][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [repositories-metering-api]
[2022-08-21T08:06:20,212][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [repository-azure]
[2022-08-21T08:06:20,213][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [repository-encrypted]
[2022-08-21T08:06:20,213][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [repository-gcs]
[2022-08-21T08:06:20,213][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [repository-s3]
[2022-08-21T08:06:20,222][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [repository-url]
[2022-08-21T08:06:20,222][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [runtime-fields-common]
[2022-08-21T08:06:20,223][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [search-business-rules]
[2022-08-21T08:06:20,223][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [searchable-snapshots]
[2022-08-21T08:06:20,224][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [snapshot-based-recoveries]
[2022-08-21T08:06:20,224][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [snapshot-repo-test-kit]
[2022-08-21T08:06:20,224][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [spatial]
[2022-08-21T08:06:20,225][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [systemd]
[2022-08-21T08:06:20,225][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [transform]
[2022-08-21T08:06:20,232][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [transport-netty4]
[2022-08-21T08:06:20,232][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [unsigned-long]
[2022-08-21T08:06:20,233][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [vector-tile]
[2022-08-21T08:06:20,233][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [vectors]
[2022-08-21T08:06:20,233][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [wildcard]
[2022-08-21T08:06:20,234][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-aggregate-metric]
[2022-08-21T08:06:20,234][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-analytics]
[2022-08-21T08:06:20,238][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-async]
[2022-08-21T08:06:20,238][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-async-search]
[2022-08-21T08:06:20,238][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-autoscaling]
[2022-08-21T08:06:20,239][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-ccr]
[2022-08-21T08:06:20,241][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-core]
[2022-08-21T08:06:20,242][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-deprecation]
[2022-08-21T08:06:20,242][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-enrich]
[2022-08-21T08:06:20,252][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-eql]
[2022-08-21T08:06:20,253][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-fleet]
[2022-08-21T08:06:20,253][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-graph]
[2022-08-21T08:06:20,253][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-identity-provider]
[2022-08-21T08:06:20,254][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-ilm]
[2022-08-21T08:06:20,254][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-logstash]
[2022-08-21T08:06:20,254][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-ml]
[2022-08-21T08:06:20,254][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-monitoring]
[2022-08-21T08:06:20,254][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-ql]
[2022-08-21T08:06:20,255][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-rollup]
[2022-08-21T08:06:20,255][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-security]
[2022-08-21T08:06:20,255][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-shutdown]
[2022-08-21T08:06:20,255][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-sql]
[2022-08-21T08:06:20,256][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-stack]
[2022-08-21T08:06:20,259][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-text-structure]
[2022-08-21T08:06:20,260][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-voting-only-node]
[2022-08-21T08:06:20,260][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-watcher]
[2022-08-21T08:06:20,262][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] no plugins loaded
[2022-08-21T08:06:20,445][INFO ][o.e.e.NodeEnvironment    ] [tpotcluster-node-01] using [1] data paths, mounts [[/data (/dev/nvme0n1p1)]], net usable_space [261.2gb], net total_space [295gb], types [ext4]
[2022-08-21T08:06:20,453][INFO ][o.e.e.NodeEnvironment    ] [tpotcluster-node-01] heap size [2gb], compressed ordinary object pointers [true]
[2022-08-21T08:06:20,943][INFO ][o.e.n.Node               ] [tpotcluster-node-01] node name [tpotcluster-node-01], node ID [j9GUWCinTYCtS58yOGDOzw], cluster name [tpotcluster], roles [data, remote_cluster_client, master, data_warm, data_content, transform, data_hot, ml, data_frozen, ingest, data_cold]
[2022-08-21T08:06:45,215][INFO ][o.e.x.s.Security         ] [tpotcluster-node-01] Security is disabled
[2022-08-21T08:06:49,319][INFO ][o.e.t.n.NettyAllocator   ] [tpotcluster-node-01] creating NettyAllocator with the following configs: [name=elasticsearch_configured, chunk_size=1mb, suggested_max_allocation_size=1mb, factors={es.unsafe.use_netty_default_chunk_and_page_size=false, g1gc_enabled=true, g1gc_region_size=4mb}]
[2022-08-21T08:06:49,424][INFO ][o.e.i.r.RecoverySettings ] [tpotcluster-node-01] using rate limit [40mb] with [default=40mb, read=0b, write=0b, max=0b]
[2022-08-21T08:06:49,667][INFO ][o.e.d.DiscoveryModule    ] [tpotcluster-node-01] using discovery type [single-node] and seed hosts providers [settings]
[2022-08-21T08:06:54,139][INFO ][o.e.n.Node               ] [tpotcluster-node-01] initialized
[2022-08-21T08:06:54,146][INFO ][o.e.n.Node               ] [tpotcluster-node-01] starting ...
[2022-08-21T08:06:54,227][INFO ][o.e.x.s.c.f.PersistentCache] [tpotcluster-node-01] persistent cache index loaded
[2022-08-21T08:06:54,228][INFO ][o.e.x.d.l.DeprecationIndexingComponent] [tpotcluster-node-01] deprecation component started
[2022-08-21T08:06:54,842][INFO ][o.e.t.TransportService   ] [tpotcluster-node-01] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
[2022-08-21T08:06:59,232][INFO ][o.e.c.c.Coordinator      ] [tpotcluster-node-01] cluster UUID [Za-6Tt9MRUSWReJrCltp7w]
[2022-08-21T08:06:59,437][INFO ][o.e.c.s.MasterService    ] [tpotcluster-node-01] elected-as-master ([1] nodes joined)[_FINISH_ELECTION_, {tpotcluster-node-01}{j9GUWCinTYCtS58yOGDOzw}{gA3FbqUGR-mlbV9zS4ljTg}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw} completing election], term: 19, version: 1899, delta: master node changed {previous [], current [{tpotcluster-node-01}{j9GUWCinTYCtS58yOGDOzw}{gA3FbqUGR-mlbV9zS4ljTg}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw}]}
[2022-08-21T08:06:59,750][INFO ][o.e.c.s.ClusterApplierService] [tpotcluster-node-01] master node changed {previous [], current [{tpotcluster-node-01}{j9GUWCinTYCtS58yOGDOzw}{gA3FbqUGR-mlbV9zS4ljTg}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw}]}, term: 19, version: 1899, reason: Publication{term=19, version=1899}
[2022-08-21T08:06:59,942][INFO ][o.e.h.AbstractHttpServerTransport] [tpotcluster-node-01] publish_address {192.168.96.4:9200}, bound_addresses {0.0.0.0:9200}
[2022-08-21T08:06:59,944][INFO ][o.e.n.Node               ] [tpotcluster-node-01] started
[2022-08-21T08:07:04,780][WARN ][o.e.x.s.i.SetSecurityUserProcessor] [tpotcluster-node-01] Creating processor [set_security_user] (tag [null]) on field [_security] but authentication is not currently enabled on this cluster  - this processor is likely to fail at runtime if it is used
[2022-08-21T08:07:05,731][INFO ][o.e.l.LicenseService     ] [tpotcluster-node-01] license [73f2418f-2f5c-4b2e-8b97-bbfb52a769b9] mode [basic] - valid
[2022-08-21T08:07:05,750][INFO ][o.e.g.GatewayService     ] [tpotcluster-node-01] recovered [23] indices into cluster_state
[2022-08-21T08:07:06,027][ERROR][o.e.i.g.GeoIpDownloader  ] [tpotcluster-node-01] exception during geoip databases update
org.elasticsearch.ElasticsearchException: not all primary shards of [.geoip_databases] index are active
        at org.elasticsearch.ingest.geoip.GeoIpDownloader.updateDatabases(GeoIpDownloader.java:135) ~[ingest-geoip-8.2.3.jar:8.2.3]
        at org.elasticsearch.ingest.geoip.GeoIpDownloader.runDownloader(GeoIpDownloader.java:275) [ingest-geoip-8.2.3.jar:8.2.3]
        at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:102) [ingest-geoip-8.2.3.jar:8.2.3]
        at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:48) [ingest-geoip-8.2.3.jar:8.2.3]
        at org.elasticsearch.persistent.NodePersistentTasksExecutor$1.doRun(NodePersistentTasksExecutor.java:42) [elasticsearch-8.2.3.jar:8.2.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-8.2.3.jar:8.2.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-8.2.3.jar:8.2.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-08-21T08:07:08,088][INFO ][o.e.i.g.DatabaseNodeService] [tpotcluster-node-01] retrieve geoip database [GeoLite2-City.mmdb] from [.geoip_databases] to [/tmp/geoip-databases/j9GUWCinTYCtS58yOGDOzw/GeoLite2-City.mmdb.tmp.gz]
[2022-08-21T08:07:08,122][INFO ][o.e.i.g.DatabaseNodeService] [tpotcluster-node-01] retrieve geoip database [GeoLite2-Country.mmdb] from [.geoip_databases] to [/tmp/geoip-databases/j9GUWCinTYCtS58yOGDOzw/GeoLite2-Country.mmdb.tmp.gz]
[2022-08-21T08:07:08,131][INFO ][o.e.i.g.DatabaseNodeService] [tpotcluster-node-01] retrieve geoip database [GeoLite2-ASN.mmdb] from [.geoip_databases] to [/tmp/geoip-databases/j9GUWCinTYCtS58yOGDOzw/GeoLite2-ASN.mmdb.tmp.gz]
[2022-08-21T08:07:09,601][INFO ][o.e.i.g.DatabaseNodeService] [tpotcluster-node-01] successfully loaded geoip database file [GeoLite2-Country.mmdb]
[2022-08-21T08:07:10,781][INFO ][o.e.i.g.DatabaseNodeService] [tpotcluster-node-01] successfully loaded geoip database file [GeoLite2-ASN.mmdb]
[2022-08-21T08:07:12,791][INFO ][o.e.m.j.JvmGcMonitorService] [tpotcluster-node-01] [gc][18] overhead, spent [377ms] collecting in the last [1.1s]
[2022-08-21T08:07:14,564][INFO ][o.e.c.r.a.AllocationService] [tpotcluster-node-01] current.health="GREEN" message="Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[logstash-2022.08.11][0]]])." previous.health="RED" reason="shards started [[logstash-2022.08.11][0]]"
[2022-08-21T08:07:15,092][INFO ][o.e.i.g.DatabaseNodeService] [tpotcluster-node-01] successfully loaded geoip database file [GeoLite2-City.mmdb]
[2022-08-21T08:32:21,298][INFO ][o.e.c.m.MetadataMappingService] [tpotcluster-node-01] [logstash-2022.08.21/TZ0GCxRnQ3muGpicoeFW6Q] update_mapping [_doc]
[2022-08-21T10:15:16,660][INFO ][o.e.c.m.MetadataMappingService] [tpotcluster-node-01] [logstash-2022.08.21/TZ0GCxRnQ3muGpicoeFW6Q] update_mapping [_doc]
[2022-08-21T10:15:17,357][INFO ][o.e.c.m.MetadataMappingService] [tpotcluster-node-01] [logstash-2022.08.21/TZ0GCxRnQ3muGpicoeFW6Q] update_mapping [_doc]
`

**Comment by t3chn0m4g3** [comment]
Last week ELK stack 8.3.3 got deoployed, it seems your T-Pot did not pull the new ES docker image and still runs with 8.2.3.

`systemctl stop tpot`
`docker pull dtagdevsec/elasticsearch:2204`
`systemctl start tpot`

**Comment by t3chn0m4g3** [comment]
Seems to be resolved.
