### ISSUE TITLE
rdpy Failing to Build as of 20221015 

### ISSUE THREAD

**Issue by k7leafclover** [telekom-security/tpotce#1188]
rdpy started failing to build today, causing T-Pot service to fail/become unstable. This is the log presented from `# docker-compose -f /opt/tpot/etc/tpot.yml build`:

```
Collecting twisted
  Downloading https://files.pythonhosted.org/packages/4a/b4/4973c7ccb5be2ec0abc779b7d5f9d5f24b17b0349e23240cfc9dc3bd83cc/Twisted-20.3.0.tar.bz2 (3.1MB)
    Complete output from command python setup.py egg_info:
    WARNING: The wheel package is not available.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qajsPi/twisted/setup.py", line 20, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 448, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 740, in finalize_options
        ep.load()(self)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/tmp/pip-install-qajsPi/twisted/.eggs/incremental-22.10.0-py2.7.egg/incremental/__init__.py", line 14, in <module>
        from typing import TYPE_CHECKING, Any, TypeVar, Union, Optional, Dict
    ImportError: No module named typing
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qajsPi/twisted/
ERROR: Service 'rdpy' failed to build: The command '/bin/sh -c sed -i 's/dl-cdn/dl-2/g' /etc/apk/repositories &&     apk -U add             build-base             git             libffi-dev             openssl             openssl-dev             python             python-dev             py-pip             py-setuptools &&     addgroup -g 2000 rdpy &&     adduser -S -s /bin/ash -u 2000 -D -g 2000 rdpy &&     pip install --no-cache-dir --upgrade cffi &&     pip install --no-cache-dir                 hpfeeds                 twisted                 pyopenssl                 qt4reactor                 service_identity                 rsa==4.5                 pyasn1 &&     mkdir -p /opt &&     cd /opt &&     git clone https://github.com/t3chn0m4g3/rdpy &&     cd rdpy &&     git checkout 1d2a4132aefe0637d09cac1a6ab83ec5391f40ca &&     python setup.py install &&     cp /root/dist/* /opt/rdpy/ &&     chown rdpy:rdpy -R /opt/rdpy/* &&     mkdir -p /var/log/rdpy &&     rm -rf /root/* &&     apk del --purge build-base                     git                     libffi-dev                     openssl-dev                     python-dev                     py-pip &&     rm -rf /var/cache/apk/*' returned a non-zero code: 1
``` 

If I comment out the rdpy service in my compose file, everything else builds fine and the service started back up fine. These hosts have been running for several years without issue and I did not make any recent manual changes.

## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`? 
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

- What edition (Standard, Nextgen, etc.) of T-Pot are you running? - Custom based on Sensor config. No modifications to rdpy config.
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? Cloud. 
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
- How long has your installation been running? A few years.

**Comment by t3chn0m4g3** [comment]
Thanks, but unfortunately this is a known issue, rdpy is no longer maintained by its developer and the reason why we decided to remove it from T-Pot since 22.04.0.
You can follow up on our upstream issue [here](https://github.com/citronneur/rdpy/issues/91).
Closing this as unsupported.

**Comment by k7leafclover** [comment]
Thank you for the quick reply and reference! I will remove it from my compose.
