### ISSUE TITLE
Dashboard TPOT Kibana show error

### ISSUE THREAD

**Issue by dhapheto** [telekom-security/tpotce#1254]
Error

Error: e.replace is not a function
    at S (https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:39045)
    at https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:41841
    at Array.filter (<anonymous>)
    at t.hasMostlyRTLItems (https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:41814)
    at https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:477:490260
    at ca (https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:399:59210)
    at Za (https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:399:68953)
    at Js (https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:399:116051)
    at Fu (https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:399:99860)
    at Pu (https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:399:99682)
![e1](https://user-images.githubusercontent.com/52807286/214794347-b793236d-2227-4316-b824-c4be6b87d960.jpg)

**Comment by dhapheto** [comment]
Error

Error: e.replace is not a function
    at S (https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:39045)
    at https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:41841
    at Array.filter (<anonymous>)
    at t.hasMostlyRTLItems (https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:6:41814)
    at https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:477:490260
    at ca (https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:399:59210)
    at Za (https://tpot.emc.id:64297/kibana/57217/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-

**Comment by t3chn0m4g3** [comment]
Thank you, seems like a bug within Kibana itself. I will look into it shortly.

**Comment by t3chn0m4g3** [comment]
New images were just built and pushed. If you want test this immediately ...
```
systemctl stop tpot
docker pull dtagdevsec/elasticsearch:2204
docker pull dtagdevsec/logstash:2204
docker pull dtagdevsec/kibana:2204
systemctl start tpot
```
