### ISSUE TITLE
HIVE install - Containers are down when I restart T-Pot

### ISSUE THREAD

**Issue by I-Simon-I** [telekom-security/tpotce#1309]
Hi

I believe I've encountered a bug with the HIVE install. I've done multiple fresh install with no modification at all and whenever I run `systemctl stop tpot` and then `systemctl start tpot` I have the following error and containers keep restarting until them all eventually start after 10 minutes ish
![image](https://user-images.githubusercontent.com/116071161/232031055-6e0c46c7-0f2b-44ae-8589-68e0b2bd42b0.png)

`journalctl -u tpot -f`
![image](https://user-images.githubusercontent.com/116071161/232031745-b06d0d9d-766d-43f3-bafc-55c61756398e.png)

I'm guessing it's not an intended feature so that's why I'm reporting it

**- What version of the OS are you currently using `lsb_release -a` and `uname  -a`**

```
 No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
`Linux statisticalperson 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux`

**- What T-Pot version are you currently using?**

> T-Pot 22.04.0

**- What edition (Standard, Nextgen, etc.) of T-Pot are you running?**

> HIVE

**- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?**

> Tried on both VM and physical

**- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.**

> No

**- How long has your installation been running?**

> About an hour (fresh install)

- Did you install upgrades, packages or use the update script?

> No

- Did you modify any scripts or configs? If yes, please attach the changes.

> No

- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/116071161/232029794-8408ff72-fac9-4ba7-9db5-01b9c935f8bf.png)
![image](https://user-images.githubusercontent.com/116071161/232029837-9b01a237-3e0c-4360-a1d6-35ff50d577ce.png)

- How much free disk space is available (`df -h`)?

> 38GB

- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/116071161/232030046-481195c2-c2c7-4796-802c-8e080593cc09.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/116071161/232030114-61f7e0d9-25b3-45b1-80ed-b8629a094472.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/116071161/232030215-5aad3324-9cc9-492a-95f4-2e4ab633128d.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries

> Error : No such container: logstash

**Comment by t3chn0m4g3** [comment]
I cannot reproduce this. Unless you provide more logs of the failing containers `docker logs <container>` there is nothing I can do to pinpoint the alleged issue.

**Comment by I-Simon-I** [comment]
The command `docker logs <container>` give me the following error when using it on DOWN containers `Error : No such container: logstash` 

However I ran it for the containers that were trying to restart over and over and here are the results :
![image](https://user-images.githubusercontent.com/116071161/232414444-41119aa2-c307-4c20-ba1e-faa8bfc01fc2.png)

Elasticsearch :

```
[2023-04-17T07:49:19,339][INFO ][o.e.n.Node               ] [tpotcluster-node-01] version[8.6.0], pid[68], build[deb/f67ef2df40237445caa70e2fef79471cc608d70d/2023-01-04T09:35:21.782467981Z], OS[Linux/5.10.0-21-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/19.0.1/19.0.1+10-21]
[2023-04-17T07:49:19,344][INFO ][o.e.n.Node               ] [tpotcluster-node-01] JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]
[2023-04-17T07:49:19,344][INFO ][o.e.n.Node               ] [tpotcluster-node-01] JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/elasticsearch, -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Xms2048m, -Xmx2048m, -XX:MaxDirectMemorySize=1073741824, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.distribution.type=deb, --module-path=/usr/share/elasticsearch/lib, --add-modules=jdk.net, -Djdk.module.main=org.elasticsearch.server]
[2023-04-17T07:49:21,345][INFO ][c.a.c.i.j.JacksonVersion ] [tpotcluster-node-01] Package versions: jackson-annotations=2.13.2, jackson-core=2.13.2, jackson-databind=2.13.2.2, jackson-dataformat-xml=2.13.2, jackson-datatype-jsr310=2.13.2, azure-core=1.27.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
[2023-04-17T07:49:22,685][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [aggregations]
[2023-04-17T07:49:22,686][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [aggs-matrix-stats]
[2023-04-17T07:49:22,686][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [analysis-common]
[2023-04-17T07:49:22,687][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [apm]
[2023-04-17T07:49:22,687][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [constant-keyword]
[2023-04-17T07:49:22,687][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [data-streams]
[2023-04-17T07:49:22,688][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [frozen-indices]
[2023-04-17T07:49:22,688][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [ingest-attachment]
[2023-04-17T07:49:22,688][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [ingest-common]
[2023-04-17T07:49:22,688][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [ingest-geoip]
[2023-04-17T07:49:22,689][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [ingest-user-agent]
[2023-04-17T07:49:22,689][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [kibana]
[2023-04-17T07:49:22,689][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [lang-expression]
[2023-04-17T07:49:22,690][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [lang-mustache]
[2023-04-17T07:49:22,690][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [lang-painless]
[2023-04-17T07:49:22,690][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [legacy-geo]
[2023-04-17T07:49:22,691][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [mapper-extras]
[2023-04-17T07:49:22,691][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [mapper-version]
[2023-04-17T07:49:22,691][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [old-lucene-versions]
[2023-04-17T07:49:22,692][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [parent-join]
[2023-04-17T07:49:22,692][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [percolator]
[2023-04-17T07:49:22,692][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [rank-eval]
[2023-04-17T07:49:22,693][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [reindex]
[2023-04-17T07:49:22,693][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [repositories-metering-api]
[2023-04-17T07:49:22,693][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [repository-azure]
[2023-04-17T07:49:22,693][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [repository-encrypted]
[2023-04-17T07:49:22,694][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [repository-gcs]
[2023-04-17T07:49:22,694][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [repository-s3]
[2023-04-17T07:49:22,695][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [repository-url]
[2023-04-17T07:49:22,695][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [runtime-fields-common]
[2023-04-17T07:49:22,695][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [search-business-rules]
[2023-04-17T07:49:22,695][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [searchable-snapshots]
[2023-04-17T07:49:22,696][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [snapshot-based-recoveries]
[2023-04-17T07:49:22,696][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [snapshot-repo-test-kit]
[2023-04-17T07:49:22,696][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [spatial]
[2023-04-17T07:49:22,696][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [systemd]
[2023-04-17T07:49:22,697][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [transform]
[2023-04-17T07:49:22,697][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [transport-netty4]
[2023-04-17T07:49:22,697][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [unsigned-long]
[2023-04-17T07:49:22,700][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [vector-tile]
[2023-04-17T07:49:22,701][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [wildcard]
[2023-04-17T07:49:22,701][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-aggregate-metric]
[2023-04-17T07:49:22,702][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-analytics]
[2023-04-17T07:49:22,702][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-async]
[2023-04-17T07:49:22,702][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-async-search]
[2023-04-17T07:49:22,703][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-autoscaling]
[2023-04-17T07:49:22,704][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-ccr]
[2023-04-17T07:49:22,704][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-core]
[2023-04-17T07:49:22,704][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-deprecation]
[2023-04-17T07:49:22,705][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-enrich]
[2023-04-17T07:49:22,705][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-eql]
[2023-04-17T07:49:22,706][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-fleet]
[2023-04-17T07:49:22,707][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-graph]
[2023-04-17T07:49:22,707][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-identity-provider]
[2023-04-17T07:49:22,708][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-ilm]
[2023-04-17T07:49:22,708][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-logstash]
[2023-04-17T07:49:22,709][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-ml]
[2023-04-17T07:49:22,709][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-monitoring]
[2023-04-17T07:49:22,709][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-ql]
[2023-04-17T07:49:22,709][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-rollup]
[2023-04-17T07:49:22,710][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-security]
[2023-04-17T07:49:22,711][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-shutdown]
[2023-04-17T07:49:22,711][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-sql]
[2023-04-17T07:49:22,711][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-stack]
[2023-04-17T07:49:22,712][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-text-structure]
[2023-04-17T07:49:22,712][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-voting-only-node]
[2023-04-17T07:49:22,712][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-watcher]
[2023-04-17T07:49:22,712][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] loaded module [x-pack-write-load-forecaster]
[2023-04-17T07:49:22,712][INFO ][o.e.p.PluginsService     ] [tpotcluster-node-01] no plugins loaded
[2023-04-17T07:49:25,232][WARN ][stderr                   ] [tpotcluster-node-01] Apr 17, 2023 7:49:25 AM org.apache.lucene.store.MMapDirectory lookupProvider
[2023-04-17T07:49:25,233][WARN ][stderr                   ] [tpotcluster-node-01] WARNING: You are running with Java 19. To make full use of MMapDirectory, please pass '--enable-preview' to the Java command line.
[2023-04-17T07:49:25,241][INFO ][o.e.e.NodeEnvironment    ] [tpotcluster-node-01] using [1] data paths, mounts [[/data (/dev/sda2)]], net usable_space [32.5gb], net total_space [41.4gb], types [ext4]
[2023-04-17T07:49:25,241][INFO ][o.e.e.NodeEnvironment    ] [tpotcluster-node-01] heap size [2gb], compressed ordinary object pointers [true]
[2023-04-17T07:49:25,306][INFO ][o.e.n.Node               ] [tpotcluster-node-01] node name [tpotcluster-node-01], node ID [_KC_kk9xTS-n5e2QPMIMfw], cluster name [tpotcluster], roles [data, data_cold, ingest, data_frozen, ml, data_hot, transform, data_content, data_warm, master, remote_cluster_client]
[2023-04-17T07:49:28,056][INFO ][o.e.x.s.Security         ] [tpotcluster-node-01] Security is disabled
[2023-04-17T07:49:28,368][INFO ][o.e.t.n.NettyAllocator   ] [tpotcluster-node-01] creating NettyAllocator with the following configs: [name=elasticsearch_configured, chunk_size=1mb, suggested_max_allocation_size=1mb, factors={es.unsafe.use_netty_default_chunk_and_page_size=false, g1gc_enabled=true, g1gc_region_size=4mb}]
[2023-04-17T07:49:28,388][INFO ][o.e.i.r.RecoverySettings ] [tpotcluster-node-01] using rate limit [40mb] with [default=40mb, read=0b, write=0b, max=0b]
[2023-04-17T07:49:28,420][INFO ][o.e.d.DiscoveryModule    ] [tpotcluster-node-01] using discovery type [single-node] and seed hosts providers [settings]
[2023-04-17T07:49:29,259][INFO ][o.e.n.Node               ] [tpotcluster-node-01] initialized
[2023-04-17T07:49:29,260][INFO ][o.e.n.Node               ] [tpotcluster-node-01] starting ...
[2023-04-17T07:49:29,274][INFO ][o.e.x.s.c.f.PersistentCache] [tpotcluster-node-01] persistent cache index loaded
[2023-04-17T07:49:29,275][INFO ][o.e.x.d.l.DeprecationIndexingComponent] [tpotcluster-node-01] deprecation component started
[2023-04-17T07:49:29,347][INFO ][o.e.t.TransportService   ] [tpotcluster-node-01] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
[2023-04-17T07:49:29,937][WARN ][o.e.c.c.ClusterBootstrapService] [tpotcluster-node-01] this node is locked into cluster UUID [z6FlnzYwSQKsAP6ow5hC8g] but [cluster.initial_master_nodes] is set to [tpotcluster-node-01]; remove this setting to avoid possible data loss caused by subsequent cluster bootstrap attempts
[2023-04-17T07:49:30,034][INFO ][o.e.c.s.MasterService    ] [tpotcluster-node-01] elected-as-master ([1] nodes joined)[_FINISH_ELECTION_, {tpotcluster-node-01}{_KC_kk9xTS-n5e2QPMIMfw}{pv7KbyRiSPSsGE3cQp2ZIw}{tpotcluster-node-01}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw} completing election], term: 136, version: 2546, delta: master node changed {previous [], current [{tpotcluster-node-01}{_KC_kk9xTS-n5e2QPMIMfw}{pv7KbyRiSPSsGE3cQp2ZIw}{tpotcluster-node-01}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw}]}
[2023-04-17T07:49:30,083][INFO ][o.e.c.s.ClusterApplierService] [tpotcluster-node-01] master node changed {previous [], current [{tpotcluster-node-01}{_KC_kk9xTS-n5e2QPMIMfw}{pv7KbyRiSPSsGE3cQp2ZIw}{tpotcluster-node-01}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw}]}, term: 136, version: 2546, reason: Publication{term=136, version=2546}
[2023-04-17T07:49:30,146][INFO ][o.e.r.s.FileSettingsService] [tpotcluster-node-01] starting file settings watcher ...
[2023-04-17T07:49:30,173][INFO ][o.e.r.s.FileSettingsService] [tpotcluster-node-01] file settings service up and running [tid=48]
[2023-04-17T07:49:30,181][INFO ][o.e.h.AbstractHttpServerTransport] [tpotcluster-node-01] publish_address {172.22.0.2:9200}, bound_addresses {0.0.0.0:9200}
[2023-04-17T07:49:30,182][INFO ][o.e.n.Node               ] [tpotcluster-node-01] started {tpotcluster-node-01}{_KC_kk9xTS-n5e2QPMIMfw}{pv7KbyRiSPSsGE3cQp2ZIw}{tpotcluster-node-01}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw}{xpack.installed=true}
[2023-04-17T07:49:30,343][INFO ][o.e.l.LicenseService     ] [tpotcluster-node-01] license [ff4889a0-4dc4-4307-b487-493185bcf30e] mode [basic] - valid
[2023-04-17T07:49:30,358][INFO ][o.e.g.GatewayService     ] [tpotcluster-node-01] recovered [15] indices into cluster_state
[2023-04-17T07:49:30,396][INFO ][o.e.h.n.s.HealthNodeTaskExecutor] [tpotcluster-node-01] Node [{tpotcluster-node-01}{_KC_kk9xTS-n5e2QPMIMfw}] is selected as the current health node.
[2023-04-17T07:49:30,398][ERROR][o.e.i.g.GeoIpDownloader  ] [tpotcluster-node-01] exception during geoip databases update org.elasticsearch.ElasticsearchException: not all primary shards of [.geoip_databases] index are active
        at org.elasticsearch.ingest.geoip@8.6.0/org.elasticsearch.ingest.geoip.GeoIpDownloader.updateDatabases(GeoIpDownloader.java:134)
        at org.elasticsearch.ingest.geoip@8.6.0/org.elasticsearch.ingest.geoip.GeoIpDownloader.runDownloader(GeoIpDownloader.java:274)
        at org.elasticsearch.ingest.geoip@8.6.0/org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:102)
        at org.elasticsearch.ingest.geoip@8.6.0/org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:48)
        at org.elasticsearch.server@8.6.0/org.elasticsearch.persistent.NodePersistentTasksExecutor$1.doRun(NodePersistentTasksExecutor.java:42)
        at org.elasticsearch.server@8.6.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:917)
        at org.elasticsearch.server@8.6.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)

[2023-04-17T07:49:31,322][INFO ][o.e.c.r.a.AllocationService] [tpotcluster-node-01] current.health="GREEN" message="Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[logstash-2023.04.16][0]]])." previous.health="RED" reason="shards started [[logstash-2023.04.16][0]]"
[2023-04-17T07:49:31,493][INFO ][o.e.i.g.DatabaseNodeService] [tpotcluster-node-01] successfully loaded geoip database file [GeoLite2-Country.mmdb]
[2023-04-17T07:49:31,559][INFO ][o.e.i.g.DatabaseNodeService] [tpotcluster-node-01] successfully loaded geoip database file [GeoLite2-ASN.mmdb]
[2023-04-17T07:49:32,321][INFO ][o.e.i.g.DatabaseNodeService] [tpotcluster-node-01] successfully loaded geoip database file [GeoLite2-City.mmdb]
[2023-04-17T07:49:44,052][INFO ][o.e.n.Node               ] [tpotcluster-node-01] stopping ...
[2023-04-17T07:49:44,054][INFO ][o.e.r.s.FileSettingsService] [tpotcluster-node-01] shutting down watcher thread
[2023-04-17T07:49:44,060][INFO ][o.e.r.s.FileSettingsService] [tpotcluster-node-01] watcher service stopped
[2023-04-17T07:49:44,063][INFO ][o.e.x.w.WatcherService   ] [tpotcluster-node-01] stopping watch service, reason [shutdown initiated]
[2023-04-17T07:49:44,064][INFO ][o.e.x.w.WatcherLifeCycleService] [tpotcluster-node-01] watcher has stopped and shutdown
[2023-04-17T07:49:44,375][INFO ][o.e.n.Node               ] [tpotcluster-node-01] stopped
[2023-04-17T07:49:44,375][INFO ][o.e.n.Node               ] [tpotcluster-node-01] closing ...
[2023-04-17T07:49:44,384][INFO ][o.e.i.g.DatabaseReaderLazyLoader] [tpotcluster-node-01] evicted [0] entries from cache after reloading database [/tmp/geoip-databases/_KC_kk9xTS-n5e2QPMIMfw/GeoLite2-Country.mmdb]
[2023-04-17T07:49:44,385][INFO ][o.e.i.g.DatabaseReaderLazyLoader] [tpotcluster-node-01] evicted [0] entries from cache after reloading database [/tmp/geoip-databases/_KC_kk9xTS-n5e2QPMIMfw/GeoLite2-ASN.mmdb]
[2023-04-17T07:49:44,385][INFO ][o.e.i.g.DatabaseReaderLazyLoader] [tpotcluster-node-01] evicted [0] entries from cache after reloading database [/tmp/geoip-databases/_KC_kk9xTS-n5e2QPMIMfw/GeoLite2-City.mmdb]
[2023-04-17T07:49:44,388][INFO ][o.e.n.Node               ] [tpotcluster-node-01] closed
```

Map Redis : 

```
1:C 17 Apr 2023 07:22:14.190 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 17 Apr 2023 07:22:14.190 # Redis version=7.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 17 Apr 2023 07:22:14.190 # Configuration loaded
1:M 17 Apr 2023 07:22:14.191 * monotonic clock: POSIX clock_gettime
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 7.0.8 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                  
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           https://redis.io       
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

1:M 17 Apr 2023 07:22:14.192 # Server initialized
1:M 17 Apr 2023 07:22:14.192 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 17 Apr 2023 07:22:14.192 * Ready to accept connections
```

Map Web : 

```
Attack Map Server 2.0.0
======== Running on http://0.0.0.0:64299 ========
(Press CTRL+C to quit)
Redis connection established.
```
Nginx :

No logs.

In case the number between the parantheses helps you : 
![image](https://user-images.githubusercontent.com/116071161/232421205-2fb7ddf5-f379-4939-9c91-758f7d079501.png)

**Comment by t3chn0m4g3** [comment]
It seems your index is corrupt... Which results in repairs followed by ES shutdowns. You can use Elasticvue to check out the details regarding the shards / index and try to delete it or repair it once all containers have started correctly.

```
[2023-04-17T07:49:30,398][ERROR][o.e.i.g.GeoIpDownloader  ] [tpotcluster-node-01] exception during geoip databases update org.elasticsearch.ElasticsearchException: not all primary shards of [.geoip_databases] index are active
        at org.elasticsearch.ingest.geoip@8.6.0/org.elasticsearch.ingest.geoip.GeoIpDownloader.updateDatabases(GeoIpDownloader.java:134)
        at org.elasticsearch.ingest.geoip@8.6.0/org.elasticsearch.ingest.geoip.GeoIpDownloader.runDownloader(GeoIpDownloader.java:274)
        at org.elasticsearch.ingest.geoip@8.6.0/org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:102)
        at org.elasticsearch.ingest.geoip@8.6.0/org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:48)
        at org.elasticsearch.server@8.6.0/org.elasticsearch.persistent.NodePersistentTasksExecutor$1.doRun(NodePersistentTasksExecutor.java:42)
        at org.elasticsearch.server@8.6.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:917)
        at org.elasticsearch.server@8.6.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

Unfortunately there is nothing more I can do at this point since this is related to ES. I recommend to research this with the ES documentation / community.

**Comment by I-Simon-I** [comment]
Alright, thx for your time
