### ISSUE TITLE
elasticsearch error: version not supported: 7.11.0 the node version is: 7.10.1

### ISSUE THREAD

**Issue by GreyDr34d** [telekom-security/tpotce#791]
Before you post your issue make sure it has not been answered yet and provide `basic support information` if you come to the conclusion it is a new issue.

- 🔍 Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- 🧐 Check our [WIKI](https://github.com/dtag-dev-sec/tpotce/wiki)
- 📚 Consult the documentation of 💻 [Debian](https://www.debian.org/doc/), 🐳 [Docker](https://docs.docker.com/), the 🦌 [ELK stack](https://www.elastic.co/guide/index.html) and the 🍯 [T-Pot Readme](https://github.com/dtag-dev-sec/tpotce/blob/master/README.md).
- **⚠️ Provide [basic support information](#info) or similiar information with regard to your issue or we can not help you and will close the issue without further notice**

<br>
<br>
<br>

<a name="info"></a>
## ⚠️ Basic support information (commands are expected to run as `root`)

- What version of the OS are you currently using `lsb_release -a` and `uname -a`?
`Linux thirstysecretariat 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux`
- What T-Pot version are you currently using?
`20.06.2`
- What edition (Standard, Nextgen, etc.) of T-Pot are you running?
`Standard`
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)?
`VM`
- Did you have any problems during the install? If yes, please attach `/install.log` `/install.err`.
`None`
- How long has your installation been running?
`Nearly one hour`
- Did you install upgrades, packages or use the update script?
`No I didn't.`
- Did you modify any scripts or configs? If yes, please attach the changes.
`No I didn't.`
- Please provide a screenshot of `glances` and `htop`.
![image](https://user-images.githubusercontent.com/40905775/111096185-ea195d80-8579-11eb-9b9f-1018d50c7cfe.png)

- How much free disk space is available (`df -h`)?
```sh
Filesystem                 Size  Used Avail Use% Mounted on
udev                       3.9G     0  3.9G   0% /dev
tmpfs                      796M   28M  769M   4% /run
/dev/mapper/tpot--vg-root   38G   11G   26G  29% /
tmpfs                      3.9G     0  3.9G   0% /dev/shm
tmpfs                      5.0M     0  5.0M   0% /run/lock
tmpfs                      3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda1                  472M   85M  363M  19% /boot
tmpfs                      796M     0  796M   0% /run/user/0
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/fe697e998244d34e802bdaae61005404cfc0c56ae6fb7e5a9f487cfd74b2ae20/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/769d2d966017bf01463640a20a42154360c51d20ccd0f938df706849e0af61d5/merged
shm                         64M     0   64M   0% /var/lib/docker/containers/db517d57af06819d2bdda3235cc94561ddf4d15cebb404291aa89483913f6268/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/3d68883fb2f7e158c5a87abd6bf3d1a68614ce1cceb46376a9f987e71d2821f8/mounts/shm
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/6a326ce688059b373492cc406d80953b183919858749609166962d5c79a2b5dd/merged
shm                         64M     0   64M   0% /var/lib/docker/containers/3ec34be8dc0b3894828cd9312f278ee5c0297718bcb71f93c610bc235cc0d3e9/mounts/shm
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/494dbb110482caae3706f552ad46171444004d579ad3afc5caed1ae7da261b9d/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/7f8427a2f407cc9d2c64f96eb72af086bf85523f31cf04716d6d9c6a0699b51a/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/339648eaaa04feed8854be5786dc047d277c9d8b24eda4c3211c02114c573866/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/cfdcdb4cd5b75ce2e29608bee292036e04795cd07feec4165a2f2aba28de137d/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/0a9f9bd9eaa3292e468750f2b58e23818d5ea16d8659e4f7454d2610a9014a4a/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/48a1d59879bd4a1100ed0a9ce6f29e2c7e435d914db6deae5ade7a28d63cc0ab/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/3aab473255c765a7cf80d004168b6831621664cfc9dad419a29ee49d614fe02e/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/72d4101471d2e67de33cccc5830bda2364e722926249257fe6c78cdc19401455/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/e2279c44e4e2fc32d9d64e966953a2160b46dbc231dff4d65dcef6747890b1ab/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/699e4cfa77c8c769cb268f8a812b31e564314db26c6fb1feb43ca91075016e4f/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/8c7ce0c5d86cfc3c9a38528591349d7782ce66b2807a038afbf80d692d8d66c0/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/8b0d57c5495a23ede5e6d0a851a65399ce5cc6fbbd3ef1bf2312f0a3b6e409be/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/de7cba29e0aa347ef75600cc3cb8adff3e09068e6816710f34b866eddd789752/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/97e0c0bd6ce60b035844d2bb3459f3160c4663595910b3536ed486e72c219368/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/a5f816a9a09efccca24b5207017b94efd27c4709814ea70f7872355c5ddf5a59/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/a57191aad75d8e6a19f1382cb7b51efcb560576984c7a29ad01ab81217b88e66/merged
shm                         64M     0   64M   0% /var/lib/docker/containers/2464b10d31645983f138e930470164c95ad38405b9425cf9d7025db19f04dd5b/mounts/shm
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/d0b7e9c4f5c330c1942a6e051b76653ae70f1ab9a7b8c424b8c551dc9f975e30/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/e5b820080bf9eb0c1543bf98605f606bf50d683ad7fd69a3fa48de55a1c0fb24/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/167e84824a36f96d35948dbe89e836d418cff58f1d9ca5a0e4f0acaffe5a5229/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/40f5852102b3309bc885bf7f1fe0ed3803e2e62141422f37075aa776b18a2c1e/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/4d81a5c803ae16023f35812eb97a9dba86e973b4ae688e0e67810e1067eed403/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/1d49c1eb9cf8e58d1721cbead36ba40fdaaf36c23682d5d4d87e590457fed2a7/merged
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/33183a3e653b54dbd661d31085855410aa3e6dba1766c3d8d6b322a083b38455/merged
shm                         64M     0   64M   0% /var/lib/docker/containers/10ce39d3c654148fbe5e0af289140cb6df332ca7c1d975863275381b7c50be11/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/0a3430dc1168dc0487230ba923babb1b6f3b943a1f250bbfe873efa6d7f1d02d/mounts/shm
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/a8bec21af8a806230e591c6d86e03470fc6d9d2e206cd49166180e806281fc52/merged
shm                         64M     0   64M   0% /var/lib/docker/containers/38a761c2d8a997b7d7daf8e42db13af830e8f85f6e48292b7b455d4f47c02d67/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/03f325723ba39ce9a854c9b2c918ea2bb79adacfaaa928890f8ec5d3484fcff7/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/7dd0491f734b567268863103e9af0ef0ef5fca1a35c8ff0856a4cc5b7202398a/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/dd28bbbdcb71c9d7d1668f04abb7398559bb8eaa755e9a15cb9044007c6e35d5/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/5ebe8263bdb600196aacb9a611f2d9db4dadb5a52522c4a57e084b21360c67eb/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/c2c1eb1aa4e0684aa7a8be9cec525fabd0325a3044dd16b7950b384244c8a342/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/2862b33b99d6d7291f41a6a4a1e01228c0189529091427b7ee3471056fbcab69/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/281f46c83ad3e67d1b936ff5d62baa9a91fef6d715c3ee94b2e74d046c31ea09/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/f6a4c93918924264b283b197c6856905f884e3f8b64ad5856f06988b000b31be/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/a150a9bc9ab1d0f32e99379c6c673b2b23971ddde39457198b97c321b3635d4e/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/5a033a9d50498ea335f77cf340cfa8147b2afcac1c52659f91d512f634558c5d/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/87c25c74d4393ee7030897908d3ababe10fa926723cf0061f0464f1fb0df672b/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/e5cd6b559f8b7a3ad3807f7dcc390b7065e4b646a32d57892c79658e07675ab1/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/3a055d32360284d89eb04c61d8231074ba511e1a5dcb3d8e7c797dee1b139407/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/7510113094bc7c1348aaef6c4c138bfb754efa4d62bbfc1c63a539c3d574bae2/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/21df7b82de3e9825f778ad8ed752a88884eb668eaa9c31e94976010e2b9deeae/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/cfcef27b823d48fe6297d71c705e868285449d2a8c78db8a84eaf9c68e4fb0d2/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/50b5e7055d109a2cb945da1b8515c4f63bba0bcfd0c449b7aa0bfba7d4236f26/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/47b221731fd6f73ed34fc5e2e97a91a8df11096155e704737ac632dce2d5ec59/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/fdbb17f59f3b41be076876c691dfaec7290b8e1b53078551a652550a53382066/mounts/shm
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/8c1aeaca7be282fc4c659238bbae27c0e039a5547758b8d79ea8af303bc3feb5/merged
shm                         64M     0   64M   0% /var/lib/docker/containers/54778d72677317ca7fff9119a72ec4f6f44ed4303937647a317d9bec6c234f9e/mounts/shm
shm                         64M     0   64M   0% /var/lib/docker/containers/61db2fd03d85b0b2e144f339523a95e6ab26119d55da851bebb2e7f67f981ede/mounts/shm
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/ea7e1e0c5d83022ad75c5869e5c381be55337667fb73cc27ac033acedfed205a/merged
shm                         64M     0   64M   0% /var/lib/docker/containers/ef8c9fc9918fa93b0ab854333630cfb2afd8d581376828d8057e1eb54676d420/mounts/shm
overlay                     38G   11G   26G  29% /var/lib/docker/overlay2/7d5b281e64ed743906bfdff596cb9459b7a4f83cab9efc999e54a20d06b8fbe2/merged
shm                         64M   20K   64M   1% /var/lib/docker/containers/954387cb9a7dc41da5dc5f924f115a5137c6c5ee49303ee6ce794d7b7dc4e12c/mounts/shm
```
- What is the current container status (`dps.sh`)?
![image](https://user-images.githubusercontent.com/40905775/111095951-7bd49b00-8579-11eb-909e-c3a26287f61d.png)

- What is the status of the T-Pot service (`systemctl status tpot`)?
![image](https://user-images.githubusercontent.com/40905775/111096236-03baa500-857a-11eb-882e-70946b5d932f.png)

- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
![image](https://user-images.githubusercontent.com/40905775/111096407-690e9600-857a-11eb-9a63-2aaabfe5c954.png)

- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
![image](https://user-images.githubusercontent.com/40905775/111096438-7f1c5680-857a-11eb-80cb-723c107fd26f.png)

Can you help me? I don't know what to do. Thanks!

**Comment by t3chn0m4g3** [comment]
Our docker images are deployed with 7.11.1. Please pull the latest images `docker-compose -f /opt/tpot/etc/tpot.yml pull`.

**Comment by GreyDr34d** [comment]
I tried the latest version but still got an error. Following is the error message.
```sh
elasticsearch    | uncaught exception in thread [main]
elasticsearch    | [2021-03-17T00:23:45,384][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [tpotcluster-node-01] uncaught exception in thread [main]
elasticsearch    | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: cannot downgrade a node from version [7.11.1] to version [7.10.1]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    | Caused by: java.lang.IllegalStateException: cannot downgrade a node from version [7.11.1] to version [7.10.1]
elasticsearch    |      at org.elasticsearch.env.NodeMetadata.upgradeToCurrentVersion(NodeMetadata.java:94) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:433) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:330) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.node.Node.<init>(Node.java:362) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.node.Node.<init>(Node.java:289) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.10.1.jar:7.10.1]
elasticsearch    |      ... 6 more
```

**Comment by t3chn0m4g3** [comment]
I cannot reproduce this. Pulled latest images from DockerHub and GitHub Container Registry. Outcome was always the same and running perfectly fine:
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2021-03-17T03:20:35,725][INFO ][o.e.n.Node               ] [tpotcluster-node-01] version[7.11.1], pid[1], build[default/tar/ff17057114c2199c9c1bbecc727003a907c0db7a/2021-02-15T13:44:09.394032Z], OS[Linux/4.19.0-14-amd64/amd64], JVM[Alpine/OpenJDK 64-Bit Server VM/11.0.9/11.0.9+11-alpine-r1]
```
Maybe some weird CDN caching is involved on your end, just a wild guess.
