### ISSUE TITLE
ERRROR : no matching indices found: no indices match pattern "logstash-*"

### ISSUE THREAD

**Issue by hd3291** [telekom-security/tpotce#825]
- What version of the OS are you currently using ?  **Debian (Stable)**
- What T-Pot version are you currently using?     **T-Pot 20.06** 
- What edition (Standard, Nextgen, etc.) of T-Pot are you running? **Standard**
- What architecture are you running on (i.e. hardware, cloud, VM, etc.)? **VMware**
- Did you have any problems during the install?  **NO**
- How long has your installation been running? **10** min 
- Did you install upgrades, packages or use the update script? **NO**
- Did you modify any scripts or configs? If yes, please attach the changes. **NO**
- Please provide a screenshot of `glances` and `htop`.
- How much free disk space is available (`df -h`)? 
- What is the current container status (`dps.sh`)?
- What is the status of the T-Pot service (`systemctl status tpot`)?
- What ports are being occupied? Stop T-Pot `systemctl stop tpot` and run `netstat -tulpen`
- If a single container shows as `DOWN` you can run `docker logs <container-name>` for the latest log entries
 
 
 After a restart this is also working. But kibana is not showing any logs
ERRROR : no matching indices found: no indices match pattern "logstash-*"

Error: Could not locate that index-pattern-field (id: @timestamp)
at FieldParamType.deserialize (https://192.168.190.135:64297/kibana/37941/bundles/plugin/data/data.plugin.js:1:661365)
at https://192.168.190.135:64297/kibana/37941/bundles/plugin/data/data.plugin.js:1:415077
at Array.forEach ()
at AggConfig.setParams (https://192.168.190.135:64297/kibana/37941/bundles/plugin/data/data.plugin.js:1:414501)
at new AggConfig (https://192.168.190.135:64297/kibana/37941/bundles/plugin/data/data.plugin.js:1:414363)
at agg_configs_AggConfigs.createAggConfig (https://192.168.190.135:64297/kibana/37941/bundles/plugin/data/data.plugin.js:1:197161)
at https://192.168.190.135:64297/kibana/37941/bundles/plugin/data/data.plugin.js:1:197513
at Array.forEach ()
at new agg_configs_AggConfigs (https://192.168.190.135:64297/kibana/37941/bundles/plugin/data/data.plugin.js:1:197492)
at Object.createAggConfigs (https://192.168.190.135:64297/kibana/37941/bundles/plugin/data/data.plugin.js:8:195209)

**Comment by hd3291** [comment]
After a restart this is also working. But  kibana is not showing any logs
ERRROR : no matching indices found: no indices match pattern "logstash-*"

**Comment by hd3291** [comment]
I cant find any logs on thr admin panel ie running on port no.64294
 Also there is no logstash service running (no directory  at /usr/share

**Comment by t3chn0m4g3** [comment]
Missing logs. Closing.
